services:
  - type: web
    name: abid-ai-portfolio-frontend
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: abid-ai-portfolio-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://abid-ai-portfolio-frontend.onrender.com
      - key: MAX_FILE_SIZE
        value: "5242880"
      - key: ALLOWED_FILE_TYPES
        value: "image/jpeg,image/png,image/gif"
    healthCheckPath: /health
    autoDeploy: true 